### ISSUE TITLE
Could there be an option for current+historical rather than current/historical?

### ISSUE THREAD

**Issue by nerdcha** [MattCowgill/readrba#3]
I hacked together my own code to pull a few tables recently, and found that I'd usually need both the "current" and "historical" versions, rbind'ed together. I think the RBA's distinction between the two is mostly about their own internal data-management workflows.

So, a feature request/suggestion — could the `cur_hist` option default to `both`?

**Comment by MattCowgill** [comment]
Ooh, great idea! I don't see why not. I guess if there are some table numbers that don't have both (ie. they have current but not historical versions, or vice versa) it would just give you what's there

**Comment by MattCowgill** [comment]
This works now! I've gone with `all` rather than `both`.

``` r

readrba::read_rba(table_no=c("a1.1"), cur_hist="all")
#> # A tibble: 29,917 x 11
#>    date       series value frequency series_type units source pub_date  
#>    <date>     <chr>  <dbl> <chr>     <chr>       <chr> <chr>  <date>    
#>  1 1994-06-01 Austr… 13680 Weekly    Original    $ mi… RBA    2020-10-09
#>  2 1994-06-08 Austr… 13055 Weekly    Original    $ mi… RBA    2020-10-09
#>  3 1994-06-15 Austr… 13086 Weekly    Original    $ mi… RBA    2020-10-09
#>  4 1994-06-22 Austr… 12802 Weekly    Original    $ mi… RBA    2020-10-09
#>  5 1994-06-29 Austr… 13563 Weekly    Original    $ mi… RBA    2020-10-09
#>  6 1994-07-06 Austr… 12179 Weekly    Original    $ mi… RBA    2020-10-09
#>  7 1994-07-13 Austr… 14325 Weekly    Original    $ mi… RBA    2020-10-09
#>  8 1994-07-20 Austr… 12563 Weekly    Original    $ mi… RBA    2020-10-09
#>  9 1994-07-27 Austr… 13638 Weekly    Original    $ mi… RBA    2020-10-09
#> 10 1994-08-03 Austr… 14801 Weekly    Original    $ mi… RBA    2020-10-09
#> # … with 29,907 more rows, and 3 more variables: series_id <chr>,
#> #   description <chr>, table_title <chr>
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for the suggestion @nerdcha

**Comment by MattCowgill** [comment]
I'm reconsidering this functionality @nerdcha. Some tables have different table numbers in the current + historical series. Or eg. in the historical series, table "E4" = "Treasury Note Tenders", but in the current series "E4" = "Household Gearing - Distribution".

**Comment by nerdcha** [comment]
Oh I see, fair enough. I hadn't explored all of them because they're annoying to deal with (which is part of why I'm excited about `readrba`).

**Comment by MattCowgill** [comment]
all good. It's in there now (`cur_hist = "all"`) but I'll think more about whether to retain it. It's in a pretty stable state now, so my intention is to tidy things up, improve the documentation, then submit to CRAN. I'll decide before then whether to keep `cur_hist = "all"`

**Comment by MattCowgill** [comment]
Having pondered this further, I think I'm going to remove the `"all"` option, @nerdcha. There's only a subset of files that have matching table numbers in the current + historical tables.
