### ISSUE TITLE
RBA formats changed to .xlsx (but filenames remain .xls)

### ISSUE THREAD

**Issue by tiprya** [MattCowgill/readrba#37]
The RBA's April updates of at least some stats tables have changed the format to an `xlsx` but the filename is still ends in `.xls`. You can verify this by opening the files manually in excel and then re-saving.

Replicate the issue:
`read_rba(table_no = c('d1', 'd2'))`

Error:
`libxls error: Unable to open file`

I don't consider this necessarily an issue with `readrba` (so feel free to delete) but thought it useful to have a central location to discuss the error. Hopefully the RBA fixes this next week.

**Comment by MattCowgill** [comment]
Hi @tiprya, I noticed this (annoying) problem the other day. I think I fixed it with this commit: https://github.com/MattCowgill/readrba/commit/38250290f7481781ca275e0e9704b6c175f6d094

Does the problem persist for you if you reinstall the GitHub version of the package?

**Comment by tiprya** [comment]
Yep that works for me!

Cheers

**Comment by MattCowgill** [comment]
Great! Thanks for raising the issue and thanks for letting me know that my fix works for you. I’ll update CRAN soon
