### ISSUE TITLE
Long-term bond yields download with missing observations

### ISSUE THREAD

**Issue by donotdespair** [MattCowgill/readrba#43]
Hi @MattCowgill 

Thank you so much for developing and maintaining this package (and others). I use it extensively for my research and teaching all my subjects at the unimelb and we're integrating your functions in reproducible pipelines for macro data analyses. The package is such a great asset!

I noticed the following problem a month ago. Long-term bond yields download with missing observations. 

Here is an illustrative example:

```
> dwnld  = readrba::read_rba(series_id = "FCMYGBAG10D")
trying URL 'https://www.rba.gov.au/statistics/tables/xls/f02d.xls'
Content type 'application/octet-stream' length 315392 bytes (308 KB)
==================================================
downloaded 308 KB

trying URL 'https://www.rba.gov.au/statistics/tables/xls-hist/f02dhist.xls'
Content type 'application/octet-stream' length 598016 bytes (584 KB)
==================================================
downloaded 584 KB

trying URL 'https://www.rba.gov.au/statistics/tables/xls-hist/f02histhist.xls'
Content type 'application/octet-stream' length 115200 bytes (112 KB)
==================================================
downloaded 112 KB

> tmp    = xts::xts(dwnld$value, dwnld$date)                               
> tmp["2013-05-10/2021-01-10"]
            [,1]
2013-05-10 3.235
2013-05-13 3.245
2013-05-14 3.240
2013-05-15 3.270
2013-05-16 3.240
2013-05-17 3.170
2021-01-04 0.980
2021-01-05 0.950
2021-01-06 1.030
2021-01-07 1.050
2021-01-08 1.090
```

So, the downloaded daily series does not contain any observations from mid-May 2013 to December 2020. 

A similar gap occurs in the monthly series:
```
> dwnld  = readrba::read_rba(series_id = "FCMYGBAG10")
trying URL 'https://www.rba.gov.au/statistics/tables/xls-hist/f02dhist.xls'
Content type 'application/octet-stream' length 598016 bytes (584 KB)
==================================================
downloaded 584 KB

trying URL 'https://www.rba.gov.au/statistics/tables/xls-hist/f02histhist.xls'
Content type 'application/octet-stream' length 115200 bytes (112 KB)
==================================================
downloaded 112 KB

trying URL 'https://www.rba.gov.au/statistics/tables/xls/f02hist.xls'
Content type 'application/octet-stream' length 30720 bytes (30 KB)
==================================================
downloaded 30 KB

> tmp    = xts::xts(dwnld$value, dwnld$date)                               
> tmp["2013-05/2021-01"]
               [,1]
2013-05-31 3.225000
2021-01-31 1.053684
```

So, I guess the RBA might have changed the file structure.

I'm sorry for not submitting a pull request with a fix and just reporting the issue. That's what time allows me to do now.

Best Regards, T

**Comment by MattCowgill** [comment]
Thanks very much @donotdespair, I'll have a look now

**Comment by MattCowgill** [comment]
Hi @donotdespair the RBA appears to have removed the data from their published tables. 

I'll do what I can do work around this.

The current version of the table includes this note: 

F2 CAPITAL MARKET YIELDS – GOVERNMENT BONDS
--
Yields are sourced from Yieldbroker Pty Limited. For any financial institution enquiries about Yieldbroker market data products please contact
marketdata@yieldbroker.com.
 
Yields are derived using linear interpolation to calculate a yield for the specified term-to-maturity. The yields used for the interpolation are sourced for the nearest nominal bond with term-to-maturity less than the specified term, and for the nearest nominal bond with term-to-maturity greater than the specified term.
 
Data previously published under Table F2 have been removed for commercial reasons.
 
For yields 1995 to 2013 see table F2 in the Historical Statistics section.

F2 CAPITAL MARKET YIELDS – GOVERNMENT BONDS
Yields are sourced from Yieldbroker Pty Limited. For any financial institution enquiries about Yieldbroker market data products please contact 
[marketdata@yieldbroker.com.](mailto:marketdata@yieldbroker.com)

Yields are derived using linear interpolation to calculate a yield for the specified term-to-maturity. The yields used for the interpolation are sourced for the nearest nominal bond with term-to-maturity less than the specified term, and for the nearest nominal bond with term-to-maturity greater than the specified term.

Data previously published under Table F2 have been removed for commercial reasons.

For yields 1995 to 2013 see table F2 in the Historical Statistics section.

F2 CAPITAL MARKET YIELDS – GOVERNMENT BONDS
--
Yields are sourced from Yieldbroker Pty Limited. For any financial institution enquiries about Yieldbroker market data products please contact
marketdata@yieldbroker.com.
 
Yields are derived using linear interpolation to calculate a yield for the specified term-to-maturity. The yields used for the interpolation are sourced for the nearest nominal bond with term-to-maturity less than the specified term, and for the nearest nominal bond with term-to-maturity greater than the specified term.
 
Data previously published under Table F2 have been removed for commercial reasons.
 
For yields 1995 to 2013 see table F2 in the Historical Statistics section.

F2 CAPITAL MARKET YIELDS – GOVERNMENT BONDS
Yields are sourced from Yieldbroker Pty Limited. For any financial institution enquiries about Yieldbroker market data products please contact 
[marketdata@yieldbroker.com.](mailto:marketdata@yieldbroker.com)

Yields are derived using linear interpolation to calculate a yield for the specified term-to-maturity. The yields used for the interpolation are sourced for the nearest nominal bond with term-to-maturity less than the specified term, and for the nearest nominal bond with term-to-maturity greater than the specified term.

Data previously published under Table F2 have been removed for commercial reasons.

For yields 1995 to 2013 see table F2 in the Historical Statistics section.

**Comment by MattCowgill** [comment]
I've contacted the RBA about this. I'm confused and dismayed. 

FYI the 2013-2021 data is available here: https://web.archive.org/web/20230321160354/https://www.rba.gov.au/statistics/tables/xls/f02d.xls 

I will try to work around this problem.

**Comment by MattCowgill** [comment]
Hi @donotdespair 
Apologies for the radio silence on this. It looks like the RBA has commenced publishing some new bond yield series! Package update incoming 

https://github.com/MattCowgill/readrba/issues/47

**Comment by donotdespair** [comment]
That's fantastic news, @MattCowgill! I'm looking forward to the updates! Happy New Year! T

**Comment by MattCowgill** [comment]
Hi @donotdespair, 
This issue now appears to be resolved! 
One note of caution: I cannot be sure that all series IDs have remained the same, with the RBA making a number of changes to their tables. So please be sure you check.

``` r
dwnld <- readrba::read_rba(series_id = "FCMYGBAG10D")

library(ggplot2)

dwnld |> 
  ggplot(aes(x = date, y = value, col = series)) +
  geom_line()
```

![](https://i.imgur.com/idpvVKh.png)

<sup>Created on 2024-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by donotdespair** [comment]
Cool! Thanks so much, @MattCowgill for this update! And once more, congrats on this package! T
