### ISSUE TITLE
FYI - API endpoint

### ISSUE THREAD

**Issue by doubleunplussed** [MattCowgill/readrba#44]
You may be aware the ASX hasn't been publishing their interbank futures PDF so far this month.

I did some digging and thought you might be interested to know that this API endpoint exists, from which you can get the settlement prices in JSON form without PDF shenanigans:

https://asx.api.markitdigital.com/asx-research/1.0/derivatives/interest-rate/IB/futures?days=1&height=179&width=179

Even if the PDFs return, hitting an API and getting JSON might be preferable!

**Comment by doubleunplussed** [comment]
Or you could scrape this page:

https://www2.asx.com.au/markets/trade-our-derivatives-market/futures-market/rba-rate-tracker

**Comment by MattCowgill** [comment]
Thanks very much @doubleunplussed!
I don't use the ASX interbank futures in this package, but do have another repo that scraped the old pdf (https://github.com/MattCowgill/cash-rate-scraper) so I'll investigate using this API to replace the PDF scraping in that repo 

Have you come across any kind of documentation for this API?

Thanks

**Comment by doubleunplussed** [comment]
Ah, apologies, I thought this repo was that repo.

No, am unaware of any documentation, I dug this particular API call out of [this page](https://www2.asx.com.au/markets/trade-our-derivatives-market/derivatives-market-prices/short-term-derivatives) via browser debugging tools.

**Comment by MattCowgill** [comment]
Thanks @doubleunp!

**Comment by MattCowgill** [comment]
Thanks @doubleunplussed !
