### ISSUE TITLE
New table F16 and changes to existing tables

### ISSUE THREAD

**Issue by benjackman** [MattCowgill/readrba#47]
Hi Matt - thanks very much for maintaining this excellent resource.

As of 29 Dec ([see here](https://www.rba.gov.au/statistics/tables/changes-to-tables.html)) we've re-published stats table F16, and made some changes to F2, F2.1, and F17 (which use F16 as a source). 

I've tested and all four of these new/updated tables work with readrba after the environment variable table_list is updated. I would do a PR, but I'm not sure how you would be able to verify that the sysdata.rda file is changed appropriately since it's a binary file. Let me know if you're happy for me to do so anyway.

The new F16 may have a bit of a beta test feel to it, and we're working to improve it over time. But feedback welcome of course.

Cheers and happy new year
Ben Jackman

**Comment by MattCowgill** [comment]
Hi @benjackman, 
Thanks so much! This is fantastic news. 
Yes, I'd be very happy if you submitted a PR. I won't be able to inspect the diff for sysdata.rda, but I'll be able to see if the updated package passes R CMD check, and that's good enough for me. 
Thanks again, happy new year to you too!
