### ISSUE TITLE
Read RBA Importing Issue

### ISSUE THREAD

**Issue by ZacTSYWA** [MattCowgill/readrba#53]
Good Morning,

The following code will not important data

read_rba(series_id = "ARBAMPCCCR")

Error is:
Error in safely_read_html(url = table_url) : 
  Could not read HTML at https://www.rba.gov.au/statistics/tables/

I am not sure what the course of this is, but the read.abs package works fine for me. Thank you in advance for your time

**Comment by MattCowgill** [comment]
Hi @ZacTSYWA 
Thanks for opening an issue. Can you please try your code again? It works fine for me - see output below. It's possible that there was some temporary issue with the RBA website that has now been resolved. 
Please let me know how you go 
Matt

``` r
library(readrba)

read_rba(series_id = "ARBAMPCCCR")
#> # A tibble: 91 × 11
#>    date       series         value frequency series_type units source pub_date  
#>    <date>     <chr>          <dbl> <chr>     <chr>       <chr> <chr>  <date>    
#>  1 1990-01-23 Change in Cas… -0.75 As annou… Original    Per … RBA    2024-02-06
#>  2 1990-02-15 Change in Cas… -0.5  As annou… Original    Per … RBA    2024-02-06
#>  3 1990-04-04 Change in Cas… -1.25 As annou… Original    Per … RBA    2024-02-06
#>  4 1990-08-02 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#>  5 1990-10-15 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#>  6 1990-12-18 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#>  7 1991-04-04 Change in Cas… -0.5  As annou… Original    Per … RBA    2024-02-06
#>  8 1991-05-16 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#>  9 1991-09-03 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#> 10 1991-11-06 Change in Cas… -1    As annou… Original    Per … RBA    2024-02-06
#> # ℹ 81 more rows
#> # ℹ 3 more variables: series_id <chr>, description <chr>, table_title <chr>
```

<sup>Created on 2024-04-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ZacTSYWA** [comment]
Yes its working fine this morning. Thanks for checking on this, much appreciated.

**Comment by MattCowgill** [comment]
No worries @ZacTSYWA, I'm glad the package(s) are of use to you!
