### ISSUE TITLE
Table F1 daily not updating past 26 August 2024

### ISSUE THREAD

**Issue by chrisschwartz-10** [MattCowgill/readrba#61]
The `read_rba` function is pulling the xls version of F1 daily, which is no longer being updated. Not sure how widespread this issue is, but there was a recent change to some tables to convert them to xlsx, breaking the urls.

`readrba::read_rba("f1")` doesn't break, but returns outdated data.

**Comment by MattCowgill** [comment]
Thanks so much for opening this issue @chrisschwartz-10, I'm on it now

**Comment by MattCowgill** [comment]
@chrisschwartz-10 Can I please check what version of the package you're on? 

If you update to the current Github version (`remotes::install_github("MattCowgill/readrba")`) then try, do you get the correct data?

**Comment by chrisschwartz-10** [comment]
@MattCowgill I've got v0.1.10, and R version 4.4.0

The dev version seems to work for me!

**Comment by MattCowgill** [comment]
Thanks @chrisschwartz-10. 

I periodically re-scrape the RBA website to obtain the current URLs for all tables, and the Github version seems to have the correct URLs. 

I'm going to:
1. Update the package on CRAN; 
2. Add an `update_urls` argument to `read_rba()` (`FALSE` by default) that will re-scrape the RBA website on demand to make sure that the correct URL(s) are used, to guard against any future issue of this sort. Working on it now.

**Comment by chrisschwartz-10** [comment]
Hey @MattCowgill, don't mean to rush you - do you have an idea of when this will be available on CRAN? Happy to keep using the dev version in the interim, just wanted to know when I can change back to the prod version.

**Comment by MattCowgill** [comment]
Hi @chrisschwartz-10 sorry for the delay. I've just submitted the update to CRAN. Should be up within 2-3 days.

**Comment by MattCowgill** [comment]
Hi @chrisschwartz-10 CRAN has published the update now. Note that it will take a day or two for binaries to be built for all platforms. https://cran.r-project.org/web/packages/readrba/index.html
